### PR TITLE
Implement resizing

### LINKED ISSUE #13: Ability to resize canvas

### PR DESCRIPTION
**Pull request by labseven**
Make Resizing the terminal work properly, closes #13.

Need to implement storing canvas separately to be able to redraw the canvas after a resize.

Todo:
- [x] `canvas_win` doesn't refresh with canvas content before first keypress
- [x] backspace doesn't write to the canvas, only to the screen.
- [x] Implement panning

### CODE REVIEW

**Comment by newsch** [comment]
I don't know if you're keeping a list of things to fix, but this is what I ran into:
- `canvas_win` doesn't refresh with canvas content before first keypress
- backspace doesn't write to the canvas, only to the screen.

**Comment by labseven** [comment]
I need to separate the canvas (model) and window (view) better, those bugs (and probably more) will be fixed by this refactor.

**Comment by labseven** [comment]
I think this is ready to be merged... let me know what you think!

**Comment by labseven** [comment]
I've just rebased against master and am ready to merge things in!

**Comment by labseven** [comment]
Note: there is no way to switch to panning mode, as the picker is not implemented.
Also, KEY_ENTER is assigned wrong on my desktop.

**Review by MatthewBeaudouinLafon — APPROVED** [review]
Looks good to me

**Pull request merged**
